### ISSUE TITLE
[MPIR-2] Dependencies report throws NullPointerException when a transitive dependency has system scope

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-project-info-reports-plugin#124]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** opened **[MPIR-2](https://issues.apache.org/jira/browse/MPIR-2?redirect=false)** and commented

DependenciesReport.java, inside getMavenProjectFromRepository( Artifact artifact, ArtifactRepository localRepository )

projectArtifact.file is always null, and when calling mavenProjectBuilder.buildFromRepository causes

java.lang.NullPointerException
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:82)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:63)
at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:377)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:343)
at org.apache.maven.report.projectinfo.DependenciesReport$DependenciesRenderer.getMavenProjectFromRepository(DependenciesReport.java:373)
at org.apache.maven.report.projectinfo.DependenciesReport$DependenciesRenderer.renderBody(DependenciesReport.java:297)
at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:65)

I've made a quick fix ignoring system dependencies, not sure if we want to change it
Inside renderBody
if ( Artifact.SCOPE_SYSTEM.equals( artifact.getScope() ) )
{
continue;
}

---

**Affects:** 2.0-beta-3

**Attachments:**
- [daveBodenPatch.txt](https://issues.apache.org/jira/secure/attachment/12717713/daveBodenPatch.txt) (_3.87 kB_)
- [patch.txt](https://issues.apache.org/jira/secure/attachment/12717755/patch.txt) (_1002 bytes_)

**Issue Links:**
- [MNG-2353](https://issues.apache.org/jira/browse/MNG-2353) mvn site:site fails generating the dependencies if the MNG-806 fix is present
 (_**"is duplicated by"**_)
- [MPIR-23](https://issues.apache.org/jira/browse/MPIR-23) Crash when processing system-scoped dependencies
 (_**"is duplicated by"**_)
- [MNG-2150](https://issues.apache.org/jira/browse/MNG-2150) Dependencies crash with NullPointerException on system dependencies
 (_**"is duplicated by"**_)
- [MPIR-24](https://issues.apache.org/jira/browse/MPIR-24) Possible NPE in DefaultArtifactResolver
 (_**"is duplicated by"**_)
- [MPIR-37](https://issues.apache.org/jira/browse/MPIR-37) Dependency report fails on system-scope dependencies
 (_**"is duplicated by"**_)
- [MSITE-125](https://issues.apache.org/jira/browse/MSITE-125) NullPointerException generating the "Dependencies" report if using system scope dependencies
 (_**"is duplicated by"**_)
- [SUREFIRE-277](https://issues.apache.org/jira/browse/SUREFIRE-277) report fails with a jar of "system" scope
 (_**"is duplicated by"**_)

2 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

artifactProject = getMavenProjectFromRepository(...) is only used to get url and description.
So, the report puts these informations in the dependencies table.

Maybe, we could add the SCOPE_SYSTEM test and thus, skipping the display of url and description.

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

Applied in svn

**Comment by jira-importer** [comment]
**[Bernd Bohmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bommel)** commented

This is a duplicate of
http://jira.codehaus.org/browse/MNG-1455

Can you apply the suggested patch please?

Or close 1455?

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Reopen to change fix version

**Comment by jira-importer** [comment]
**[Julian Wood](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=woodj)** commented

I'm still seeing this issue as of maven 2.0.4, May 2nd, 2006. So still can't make a dependency report if there is a system-scoped dep.

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

You need to use the 2.0 version of the maven-project-info-report plugin, that will be released in the following days

**Comment by jira-importer** [comment]
**[Matthew Beermann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mbeerman)** commented

I don't have the authority to reopen bugs, but I just tested using the 2.0 version of MPIR and the bug still seems to be present. The NPE is in the same place; however, the stack trace looks slightly different from the one originally posted here...

[INFO] Generate "Dependencies" report.
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
java.lang.NullPointerException
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:82)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:63)
at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:467)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:225)
at org.apache.maven.report.projectinfo.DependenciesReport$DependenciesRenderer.getMavenProjectFromRepository(DependenciesReport.java:456)
at org.apache.maven.report.projectinfo.DependenciesReport$DependenciesRenderer.printDescriptionsAndURLs(DependenciesReport.java:392)
at org.apache.maven.report.projectinfo.DependenciesReport$DependenciesRenderer.printDescriptionsAndURLs(DependenciesReport.java:429)
at org.apache.maven.report.projectinfo.DependenciesReport$DependenciesRenderer.renderBody(DependenciesReport.java:277)
at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:65)
at org.apache.maven.report.projectinfo.DependenciesReport.executeReport(DependenciesReport.java:97)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:101)
at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:67)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:239)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:115)
at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:124)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:92)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:475)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:454)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

reopened per user comment

**Comment by jira-importer** [comment]
**[Matthew Beermann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mbeerman)** commented

Note: This is the identical patch to the one from MNG-1455, which was resolved as a duplicate of this issue - without applying the patch. So somebody please actually CHECK IT IN this time. :)

**Comment by jira-importer** [comment]
**[Joel Wiegman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jwiegman)** commented

This bug should not be closed.  It is still happening in 2.0.7.   Calling "mvn site:site" generates the following stack trace:

[INFO] Generating "Dependencies" report.
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:991)
at java.lang.Double.parseDouble(Double.java:482)
at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderSectionDependencyFileDetails(DependenciesRenderer.java:375)
at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderBody(DependenciesRenderer.java:165)
at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:65)
at org.apache.maven.report.projectinfo.DependenciesReport.executeReport(DependenciesReport.java:140)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:101)
at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:139)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:266)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:99)
at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:130)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:97)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:493)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:463)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:280)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

open a new issue
