### ISSUE TITLE
[MPIR-3] Dependency report breaks on systemPath artifacts

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-project-info-reports-plugin#125]
**[Wilfred Springer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wilfred)** opened **[MPIR-3](https://issues.apache.org/jira/browse/MPIR-3?redirect=false)** and commented

My project refers to several artifacts that have a \<systemPath> element, refering to jar files in the ${basedir}/lib directory. The projects builds fine, but the dependency reports breaks when it starts processing these dependencies.

java.lang.NullPointerException
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:82)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:63)
at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:380)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:346)
at org.apache.maven.report.projectinfo.DependenciesReport$DependenciesRenderer.getMavenProjectFromRepository(DependenciesReport.java:362)
at org.apache.maven.report.projectinfo.DependenciesReport$DependenciesRenderer.renderBody(DependenciesReport.java:242)
at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:65)
at org.apache.maven.report.projectinfo.DependenciesReport.executeReport(DependenciesReport.java:157)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:98)
at org.apache.maven.plugins.site.SiteMojo.generateReportsPages(SiteMojo.java:789)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:301)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:399)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:519)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:482)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:452)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:301)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:268)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:137)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:316)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:113)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---

**Issue Links:**
- [MPIR-24](https://issues.apache.org/jira/browse/MPIR-24) Possible NPE in DefaultArtifactResolver
 (_**"duplicates"**_)

4 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Geoffrey Wiseman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=diathesis)** commented

Seem to have the same problem here.

**Comment by jira-importer** [comment]
**[Jeff Jensen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jeffjensen)** commented

Same here.

**Comment by jira-importer** [comment]
**[Thomas Van de Velde](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thomas.vdvelde)** commented

I have a nullpointer under these conditions:

\<project xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance
"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd ">

    <modelVersion>4.0.0</modelVersion>
    <parent>
    	<groupId>com.whatever.more.prm</groupId>
    	<artifactId>prm-project</artifactId>
    	<version>1.0</version>
    
    </parent>
    <artifactId>prm-prototype</artifactId>
    <groupId>com.whataever.more.prm.proto</groupId>
    <packaging>jar</packaging>
    <name>PRM Prototype</name>
    
    <dependencies>
    	<dependency>
    		<artifactId>mysql-connector-java</artifactId>
    		<groupId>mysql</groupId>
    		<version>3.0.10</version>
    		<scope>provided</scope>
    
    	</dependency>
    	<dependency>
    		<artifactId>junit</artifactId>
    		<groupId>junit</groupId>
    		<version>3.8.1</version>
    		<scope>test</scope>
    
    	</dependency>
    	<dependency>
    		<artifactId>spring-webmvc</artifactId>
    		<groupId>springframework</groupId>
    		<version>1.2.5</version>
    	</dependency>
    
    	<dependency>
    		<artifactId>geronimo-spec-jta</artifactId>
    		<groupId>geronimo-spec</groupId>
    		<version>1.0-M1</version>
    		<scope>provided</scope>
    
    	</dependency>
    	<dependency>
    		<artifactId>spring-hibernate</artifactId>
    		<groupId>springframework</groupId>
    		<version>1.2.5</version>
    		<exclusions>
    
    			<exclusion>
    				<artifactId>toplink-api</artifactId>
    				<groupId>com.oracle</groupId>
    			</exclusion>
    			<exclusion>
    				<artifactId>jacc</artifactId>
    
    				<groupId>javax.security</groupId>
    			</exclusion>
    			<exclusion>
    				<artifactId>ejb</artifactId>
    				<groupId>javax.persistence</groupId>
    			</exclusion>
    
    			<exclusion>
    				<artifactId>jdo</artifactId>
    				<groupId>javax.jdo</groupId>
    			</exclusion>				
    		</exclusions>
    	</dependency>
    	<dependency>
    
    		<artifactId>spring-mock</artifactId>
    		<groupId>springframework</groupId>
    		<version>1.2.5</version>
    		<exclusions>
    			<exclusion>
    				<artifactId>jta</artifactId>
    
    				<groupId>javax.transaction</groupId>
    			</exclusion>
    			<exclusion>
    				<artifactId>jdbc-stdext</artifactId>
    				<groupId>javax.sql</groupId>
    			</exclusion>
    
    			<exclusion>
    				<artifactId>jsf-api</artifactId>
    				<groupId>javax.faces</groupId>
    			</exclusion>
    		</exclusions>
    	</dependency>
    </dependencies>

\</project>

and the one I extend from:

\<project>
	\<modelVersion>4.0.0\</modelVersion>
	\<groupId>com.whatever.more.prm\</groupId>
	\<version>1.0\</version>
	\<artifactId>prm-project\</artifactId>

    <packaging>pom</packaging>
    <name>Whatever Project</name>
    <modules>
    	<module>proto</module>
    </modules>
      <build>
        <plugins>
    
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
    
                    <source>1.5</source>
                    <target>1.5</target>
                </configuration>
             </plugin>
         </plugins>
      </build>

\</project>

**Comment by jira-importer** [comment]
**[Bernd Bohmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bommel)** commented

Please vote for http://jira.codehaus.org/browse/MNG-1455
