### ISSUE TITLE
[MPIR-374] Unknown packaging: bundle when creating report

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-project-info-reports-plugin#226]
**[Peter Lamby](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=serra)** opened **[MPIR-374](https://issues.apache.org/jira/browse/MPIR-374?redirect=false)** and commented

After I upgraded the plugin to 3.0.0 I get the following errors:

```
[INFO] Generating "Dependency Management" report --- maven-project-info-reports-plugin:3.0.0:dependency-management
[WARNING] Unable to create Maven project for com.fasterxml.jackson.module:jackson-module-scala_2.10:jar:2.9.5 from repository.
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Unknown packaging: bundle @ line 6, column 16

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:192)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:327)
	at org.apache.maven.report.projectinfo.dependencies.RepositoryUtils.getMavenProjectFromRepository(RepositoryUtils.java:125)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.getDependencyRow(DependencyManagementRenderer.java:253)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderDependenciesForScope(DependencyManagementRenderer.java:202)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderDependenciesForAllScopes(DependencyManagementRenderer.java:151)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderSectionProjectDependencies(DependencyManagementRenderer.java:144)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderBody(DependencyManagementRenderer.java:130)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:80)
	at org.apache.maven.report.projectinfo.DependencyManagementReport.executeReport(DependencyManagementReport.java:107)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:251)
	at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:230)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:349)
	at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:198)
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:147)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for com.fasterxml.jackson.module:jackson-module-scala_2.10:2.9.5
[ERROR] Unknown packaging: bundle @ line 6, column 16

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:197)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:482)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:424)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:414)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:158)
	... 36 more
[WARNING] Unable to create Maven project for com.fasterxml.jackson.module:jackson-module-scala_2.11:jar:2.9.5 from repository.
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Unknown packaging: bundle @ line 6, column 16

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:192)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:327)
	at org.apache.maven.report.projectinfo.dependencies.RepositoryUtils.getMavenProjectFromRepository(RepositoryUtils.java:125)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.getDependencyRow(DependencyManagementRenderer.java:253)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderDependenciesForScope(DependencyManagementRenderer.java:202)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderDependenciesForAllScopes(DependencyManagementRenderer.java:151)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderSectionProjectDependencies(DependencyManagementRenderer.java:144)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderBody(DependencyManagementRenderer.java:130)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:80)
	at org.apache.maven.report.projectinfo.DependencyManagementReport.executeReport(DependencyManagementReport.java:107)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:251)
	at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:230)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:349)
	at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:198)
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:147)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for com.fasterxml.jackson.module:jackson-module-scala_2.11:2.9.5
[ERROR] Unknown packaging: bundle @ line 6, column 16

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:197)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:482)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:424)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:414)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:158)
	... 36 more
[WARNING] Unable to create Maven project for com.fasterxml.jackson.module:jackson-module-scala_2.12:jar:2.9.5 from repository.
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Unknown packaging: bundle @ line 6, column 16

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:192)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:327)
	at org.apache.maven.report.projectinfo.dependencies.RepositoryUtils.getMavenProjectFromRepository(RepositoryUtils.java:125)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.getDependencyRow(DependencyManagementRenderer.java:253)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderDependenciesForScope(DependencyManagementRenderer.java:202)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderDependenciesForAllScopes(DependencyManagementRenderer.java:151)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderSectionProjectDependencies(DependencyManagementRenderer.java:144)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderBody(DependencyManagementRenderer.java:130)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:80)
	at org.apache.maven.report.projectinfo.DependencyManagementReport.executeReport(DependencyManagementReport.java:107)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:251)
	at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:230)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:349)
	at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:198)
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:147)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for com.fasterxml.jackson.module:jackson-module-scala_2.12:2.9.5
[ERROR] Unknown packaging: bundle @ line 6, column 16

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:197)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:482)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:424)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:414)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:158)
	... 36 more
[WARNING] Unable to create Maven project for org.postgresql:postgresql:jar:42.2.2 from repository.
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Unknown packaging: bundle @ line 11, column 14

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:192)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:327)
	at org.apache.maven.report.projectinfo.dependencies.RepositoryUtils.getMavenProjectFromRepository(RepositoryUtils.java:125)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.getDependencyRow(DependencyManagementRenderer.java:253)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderDependenciesForScope(DependencyManagementRenderer.java:202)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderDependenciesForAllScopes(DependencyManagementRenderer.java:151)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderSectionProjectDependencies(DependencyManagementRenderer.java:144)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderBody(DependencyManagementRenderer.java:130)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:80)
	at org.apache.maven.report.projectinfo.DependencyManagementReport.executeReport(DependencyManagementReport.java:107)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:251)
	at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:230)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:349)
	at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:198)
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:147)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for org.postgresql:postgresql:42.2.2
[ERROR] Unknown packaging: bundle @ line 11, column 14

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:197)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:482)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:424)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:414)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:158)
	... 36 more
```

You can find the project that exhibits the problem here: https://github.com/Serranya/ballot/tree/mpir-bug-report
Build with ```
mvn -Pfatjar,dev clean package site:site

```
```

---

**Affects:** 3.0.0, 3.1.0

**Issue Links:**
- [MPIR-373](https://issues.apache.org/jira/browse/MPIR-373) Upgrade from 2.9 to 3.0.0 introduces additional warning
 (_**"duplicates"**_)
- [HBASE-26535](https://issues.apache.org/jira/browse/HBASE-26535) [site, branch-2] DependencyManagement report is broken
 (_**"causes"**_)
- [MPIR-366](https://issues.apache.org/jira/browse/MPIR-366) Drop Maven 2 support
 (_**"is caused by"**_)
- [MDEP-630](https://issues.apache.org/jira/browse/MDEP-630) error dependency:list (caused by postgresql dependency)

- [MPIR-373](https://issues.apache.org/jira/browse/MPIR-373) Upgrade from 2.9 to 3.0.0 introduces additional warning

- [MPIR-429](https://issues.apache.org/jira/browse/MPIR-429) avoid warning on "Unknown packaging: bundle"
 (_**"is superceded by"**_)

**Remote Links:**
- [GitHub Pull Request #15
](https://github.com/apache/maven-project-info-reports-plugin/pull/15)

**Backported to:** [3.0.1](https://github.com/apache/maven-project-info-reports-plugin/milestone/21?closed=1)

7 votes, 17 watchers

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Something is broken in the dep chain. This seems to be a transitive dep and some dependendent did not declare the package nor does the POM define an extension for the custom packaging. [Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte), what do you think?

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

I wonder if the packaging is interesting for creating reports, it is only there for build instructions. Its value should be ignorable.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte), not the value is of interesent, but the behavior.Look at the PostgreSQL JDBC driver, it is a bundle and its parent has the Maven Bundle Plugin as extension activated. That should not lead to an error, should it?

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Agree, it should not.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Serra](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Serra), is there a way to have a minimal project? This one seems to be huge to isolate the issue.

**Comment by jira-importer** [comment]
**[Peter Lamby](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=serra)** commented

[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o), I created a modified quickstart at https://github.com/Serranya/mpir374

**Comment by jira-importer** [comment]
**[Mikaël Geljić](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgeljic)** commented

Hi there, may I relate this issue to MPIR-373?

Both are similar in that the reports produce hefty stack traces for remote POM issues, which are otherwise not reported in the default lifecycle. As this involves few established 3rd-party deps (on central) there is little option to do anything about them, in this case maybe for the lack of MNG-5600. ;)

We therefore "inherit" a mix of _unknown packaging_, deprecated expressions or missing plugin versions, as illustrated below (omitting 175 lines of stack traces):

```
[INFO] Generating "Dependencies" report  --- maven-project-info-reports-plugin:3.0.0:dependencies
[WARNING] Unable to create Maven project from repository.
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 153, column 15
[WARNING] The expression ${pom.build.sourceDirectory} is deprecated. Please use ${project.build.sourceDirectory} instead. @ 
[ERROR] 'distributionManagement.status' must not be specified. @ line 237, column 13
```

Cheers,

**Comment by jira-importer** [comment]
**[Michael Düsterhus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=reitzmichnicht)** commented

Please this is annoying having a zero warning policy. 

A workaround is to disable the logger:
-Dorg.slf4j.simpleLogger.log.org.apache.maven.report.projectinfo.DependencyManagementReport=ERROR

**Comment by jira-importer** [comment]
**[Bernhard Mähr](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmaehr)** commented

Would it be possible to release this plugin to get rid of this annoying messages by [Alexander Gängel](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agaengel) bugfix?

 

[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte) [Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)

**Comment by jira-importer** [comment]
**[Bernhard Mähr](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmaehr)** commented

[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o) My fault, the fix should be already in 3.0.1 but 3.0.1 is released but not available in the maven repository and not listed as latest version on the plugin homepage.
Could you start this publish process?

[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy) perhaps?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Reopening as per request.

**Comment by jira-importer** [comment]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** commented

Done in [3e139cdbafc944932407ae349da0c54fbf433e50](https://gitbox.apache.org/repos/asf?p=maven-project-info-reports-plugin.git;a=commit;h=3e139cdbafc944932407ae349da0c54fbf433e50)

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

for the record: does not really solves the root cause per-se, but limits the WARN output to one line (not displaying the stacktrace) when not in debug mode
