### ISSUE TITLE
[MPIR-29] Invalid groupId in dependency pom fails dependencies report with an IAE

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-project-info-reports-plugin#353]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** opened **[MPIR-29](https://issues.apache.org/jira/browse/MPIR-29?redirect=false)** and commented

Happens with 2.0-SNAPSHOT

The Error could be caught and converted in a non fatal error.

[...]
[INFO] Generate "Dependencies" report.
[INFO] ----------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] Can't find a valid Maven project in the repository for the artifact [com.sun.jdmk:jmxtools:1.2.1].
[INFO] ----------------------------------------------------------------------------
[INFO] Trace
java.lang.IllegalArgumentException: Can't find a valid Maven project in the repository for the artifact [com.sun.jdmk:jmxtools:1.2.1].
at org.apache.maven.report.projectinfo.DependenciesReport$DependenciesRenderer.renderBody(DependenciesReport.java:246)
at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:65)
at org.apache.maven.report.projectinfo.DependenciesReport.executeReport(DependenciesReport.java:157)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:98)
at org.apache.maven.plugins.site.SiteMojo.generateReportsPages(SiteMojo.java:1046)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:397)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:415)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:531)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:472)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:303)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:270)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:139)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---
No further details from [MPIR-29](https://issues.apache.org/jira/browse/MPIR-29?redirect=false)

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

Works for me when calling
mvn site or mvn project-info-reports:dependencies

[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] Failed to resolve artifact.

required artifacts missing:
com.sun.jdmk:jmxtools:jar:1.2.1

**Comment by jira-importer** [comment]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** commented

I haven't tried to reproduce it neither today but do we really want to fail the whole site creation when a particular report fail?
Furthermore can't we have a better error message than just an exception?

Given the stack trace, something can be done to make the plugin a little bit more user friendly..
