### ISSUE TITLE
[MPIR-37] Dependency report fails on system-scope dependencies

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-project-info-reports-plugin#359]
**[Helge Olav Aarstein](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=helgeaa)** opened **[MPIR-37](https://issues.apache.org/jira/browse/MPIR-37?redirect=false)** and commented

Dependency to local weblogic.jar causes the dependency project report to fail.

Error caused by following dependency setting in the pom.xml -file:
\<dependency>
\<groupId>com.bea.weblogic\</groupId>
\<artifactId>webservices\</artifactId>
\<version>9.1.0\</version>
\<scope>system\</scope>
\<systemPath>${wls910.server.lib}/weblogic.jar\</systemPath>
\</dependency>

If I put weblogic.jar into the repository the dependency report seems to work fine, but then my compile fails (but that's a completely different story and should not affect this problem).

Stacktrace follows:
[INFO] Generate "Dependencies" report.
[INFO] ----------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] null
[INFO] ----------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:82)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:63)
at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:386)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:351)
at org.apache.maven.report.projectinfo.DependenciesReport$DependenciesRenderer.getMavenProjectFromRepository(DependenciesReport.java:362)
at org.apache.maven.report.projectinfo.DependenciesReport$DependenciesRenderer.renderBody(DependenciesReport.java:242)
at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:65)
at org.apache.maven.report.projectinfo.DependenciesReport.executeReport(DependenciesReport.java:157)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:98)
at org.apache.maven.plugins.site.SiteMojo.generateReportsPages(SiteMojo.java:802)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:301)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:415)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:531)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:47

---

**Affects:** 2.0

**Issue Links:**
- [MPIR-2](https://issues.apache.org/jira/browse/MPIR-2) Dependencies report throws NullPointerException when a transitive dependency has system scope
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I think this is already fixed, but will review for 2.0

**Comment by jira-importer** [comment]
**[Matt Read](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mread@spotd.co.uk)** commented

I'm experiencing this using v2.0. Can it be re-opened or should I log another issue?

**Comment by jira-importer** [comment]
**[Helge Olav Aarstein](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=helgeaa)** commented

Try downloading updated maven package (2.0.4 fixed the problem for me)

**Comment by jira-importer** [comment]
**[Matt Read](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mread@spotd.co.uk)** commented

I'm using Maven 2.0.4 but perhaps not the latest version of the site plugin due to problems with codehaus.org. I'll wait a couple of days until they are resolved before trying again. Thanks for replying.

**Comment by jira-importer** [comment]
**[Julian Wood](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=woodj)** commented

I think it should be reopened. It fails for me. I'm using mvn 2.0.4 and 2.0-beta-6-SNAPSHOT (rev 414979) of the site plugin.

    <dependency>
        <groupId>com.apple.quicktime</groupId>
        <artifactId>qtjava</artifactId>
        <version>6.4</version>
        <scope>system</scope>
        <systemPath>/System/Library/Java/Extensions/QTJava.zip</systemPath>
    </dependency>

**Comment by jira-importer** [comment]
**[Julian Wood](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=woodj)** commented

Sorry, I spoke too soon. Site plugin doesn't matter, it's project-info-reports-plugin that is the culprit. The problem exists in the released version (2.0) but is fixed in 2.1-SNAPSHOT.

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

You need 2.0.1 of project info report plugin, see MPIR-2
