### ISSUE TITLE
[MPIR-73] Error when running task deploy en maven2.x

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-project-info-reports-plugin#383]
**[Luiz Alberto da Cruz Rangel Junior](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lalberto)** opened **[MPIR-73](https://issues.apache.org/jira/browse/MPIR-73?redirect=false)** and commented

java.lang.NullPointerException
at org.codehaus.plexus.i18n.DefaultI18N.getBundle(DefaultI18N.java:141)
at org.apache.maven.plugins.site.AbstractSiteMojo.getAvailableLocales(AbstractSiteMojo.java:166)
at org.apache.maven.plugins.site.SiteDescriptorAttachMojo.execute(SiteDescriptorAttachMojo.java:67)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:475)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:454)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---
No further details from [MPIR-73](https://issues.apache.org/jira/browse/MPIR-73?redirect=false)

**Comment by jira-importer** [comment]
**[Luiz Alberto da Cruz Rangel Junior](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lalberto)** commented

Microsoft Windows XP [versão 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

C:\Documents and Settings\continuum>cd..

C:\Documents and Settings>cd..

C:\>mvn help:describe -Dplugin=project-info-reports
'mvn' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

C:\>cd jcompanyqa

C:\jCompanyQa>cd maven2

C:\jCompanyQa\maven2>cd bin

C:\jCompanyQa\maven2\bin>mvn help:describe -Dplugin=project-info-reports
[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'help'.
[INFO] org.apache.maven.plugins: checking for updates from central
[INFO] org.codehaus.mojo: checking for updates from central
[INFO] artifact org.apache.maven.plugins:maven-help-plugin: checking for updates from central
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = 'bf2b9cb1785dc1038d20ccef6c607895aeebf818'; remote
= 'fba26551f9f71795c700c507aa6be94f22492059' - RETRYING
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = 'bf2b9cb1785dc1038d20ccef6c607895aeebf818'; remote
= 'fba26551f9f71795c700c507aa6be94f22492059' - IGNORING
Downloading: http://10.14.52.25:8000/maven/org/apache/maven/plugins/maven-help-plugin/2.0.1/maven-help-plugin-2.0.1.pom
1K downloaded
Downloading: http://10.14.52.25:8000/maven/org/apache/maven/plugins/maven-help-plugin/2.0.1/maven-help-plugin-2.0.1.jar
19K downloaded
[INFO] ----------------------------------------------------------------------------
[INFO] Building Maven Default Project
[INFO]    task-segment: [help:describe] (aggregator-style)
[INFO] ----------------------------------------------------------------------------
Downloading: http://10.14.52.25:8000/maven/org/apache/maven/maven-plugin-tools-api/2.0/maven-plugin-tools-api-2.0.pom
865b downloaded
Downloading: http://10.14.52.25:8000/maven/org/apache/maven/maven-plugin-tools/2.0/maven-plugin-tools-2.0.pom
536b downloaded
Downloading: http://10.14.52.25:8000/maven/org/apache/maven/maven-plugin-descriptor/2.0/maven-plugin-descriptor-2.0.pom
1K downloaded
Downloading: http://10.14.52.25:8000/maven/org/apache/maven/maven-core/2.0/maven-core-2.0.pom
5K downloaded
Downloading: http://10.14.52.25:8000/maven/org/apache/maven/maven-plugin-parameter-documenter/2.0/maven-plugin-parameter
-documenter-2.0.pom
1K downloaded
Downloading: http://10.14.52.25:8000/maven/org/apache/maven/maven-error-diagnostics/2.0/maven-error-diagnostics-2.0.pom
812b downloaded
Downloading: http://10.14.52.25:8000/maven/org/apache/maven/maven-monitor/2.0/maven-monitor-2.0.pom
400b downloaded
Downloading: http://10.14.52.25:8000/maven/org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity
-api-1.0-alpha-4.pom
6K downloaded
Downloading: http://10.14.52.25:8000/maven/org/apache/maven/wagon/wagon-http-lightweight/1.0-alpha-5/wagon-http-lightwei
ght-1.0-alpha-5.pom
5K downloaded
Downloading: http://10.14.52.25:8000/maven/org/apache/maven/wagon/wagon-file/1.0-alpha-5/wagon-file-1.0-alpha-5.pom
5K downloaded
Downloading: http://10.14.52.25:8000/maven/commons-cli/commons-cli/1.0/commons-cli-1.0.pom
2K downloaded
Downloading: http://10.14.52.25:8000/maven/org/apache/maven/wagon/wagon-ssh/1.0-alpha-5/wagon-ssh-1.0-alpha-5.pom
6K downloaded
Downloading: http://10.14.52.25:8000/maven/com/jcraft/jsch/0.1.23/jsch-0.1.23.pom
485b downloaded
Downloading: http://10.14.52.25:8000/maven/org/apache/maven/maven-plugin-registry/2.0/maven-plugin-registry-2.0.pom
1K downloaded
Downloading: http://10.14.52.25:8000/maven/org/apache/maven/maven-plugin-tools-api/2.0/maven-plugin-tools-api-2.0.jar
22K downloaded
[INFO] [help:describe]
[INFO] artifact org.apache.maven.plugins:maven-project-info-reports-plugin: checking for updates from central
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = 'ab29fc896cc16460e782aa3db8f20241557c57f7'; remote
= 'b9548ee5b46458a4f104f03940da110173215943' - RETRYING
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = 'ab29fc896cc16460e782aa3db8f20241557c57f7'; remote
= 'b9548ee5b46458a4f104f03940da110173215943' - IGNORING
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: org.apache.maven.plugins:maven-project-info-reports-plugin

Reason: Error getting POM for 'org.apache.maven.plugins:maven-project-info-reports-plugin' from the repository: Failed t
o resolve artifact, possibly due to a repository list that is not appropriately equipped for this artifact's metadata.
org.apache.maven.plugins:maven-project-info-reports-plugin:pom:2.1-SNAPSHOT

from the specified remote repositories:
central (http://repo1.maven.org/maven2)

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3 seconds
[INFO] Finished at: Mon Oct 15 06:38:28 GMT 2007
[INFO] Final Memory: 2M/5M
[INFO] ------------------------------------------------------------------------

C:\jCompanyQa\maven2\bin>

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

I believe that this issue belongs in the site-plugin and occurs because of a missing property in the ResourceBundle. What locale do you have on your machine?

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

should be fixed with MPIR-79
