### ISSUE TITLE
[MPIR-103] Unable to find summary mojo

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-project-info-reports-plugin#404]
**[Zach Legein](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zlegein)** opened **[MPIR-103](https://issues.apache.org/jira/browse/MPIR-103?redirect=false)** and commented

Getting this error when running this snapshot

Error getting reports from the plugin 'org.apache.maven.plugins:maven-project-info-reports-plugin': Unable to find the mojo 'org.apache.maven.plugins:maven-project-info-reports-plugin:2.2-SNAPSHOT:summary' in the plugin 'org.apache.maven.plugins:maven-project-info-reports-plugin'

---

**Affects:** 2.1.1

**Issue Links:**
- [MSHARED-23](https://issues.apache.org/jira/browse/MSHARED-23) SiteToolException: Error reading default site descriptor: ${OUTPUTENCODING}

- [MPIR-101](https://issues.apache.org/jira/browse/MPIR-101) Update to Doxia 1.1

**Comment by jira-importer** [comment]
**[Zach Legein](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zlegein)** commented

seems to be

Caused by: java.lang.NoClassDefFoundError: org/apache/maven/doxia/logging/Log
at java.lang.Class.getDeclaredConstructors0(Native Method)
at java.lang.Class.privateGetDeclaredConstructors(Class.java:2389)
at java.lang.Class.getConstructor0(Class.java:2699)
at java.lang.Class.newInstance0(Class.java:326)
at java.lang.Class.newInstance(Class.java:308)
at org.codehaus.plexus.component.factory.java.JavaComponentFactory.newInstance(JavaComponentFactory.java:44)
... 34 more
Caused by: java.lang.ClassNotFoundException: org.apache.maven.doxia.logging.Log
at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
at org.codehaus.classworlds.RealmClassLoader.loadClassDirect(RealmClassL

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

As per MPIR-101, this plugin snapshot has been updated to use Doxia 1.0-beta-1. This Doxia version in turn requires Maven 2.0.10-SNAPSHOT.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Bumping the maven prerequisites to 2.0.10-SNAPSHOT for this plugin should give the user a better error message.
