### ISSUE TITLE
[MPIR-134] SCM report generator should adhere to maven.scm.provider.cvs.implementation property

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-project-info-reports-plugin#432]
**[Ringo De Smet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ringods)** opened **[MPIR-134](https://issues.apache.org/jira/browse/MPIR-134?redirect=false)** and commented

I have a number of projects correctly building with Maven 2.0.9. I now came to the point that I wanted to tackle the site generation.
Everything works, except the SCM report because it seems to insist on using the Java based CVS library. I already had to revert to scm_native for the release plugin, so I would have assumed that this would have worked for the project-info-reports also.

The command-line I use:

```
mvn site -Dmaven.scm.provider.cvs.implementation=cvs_native -Dusername=rdesmet1
```

The error I get:

```
...
[INFO] Generating "Source Xref" report.
[INFO] Generating "Continuous Integration" report.
[INFO] Generating "Dependencies" report.
[INFO] Generating "Issue Tracking" report.
[INFO] Generating "Project License" report.
[INFO] Generating "Mailing Lists" report.
[INFO] Generating "Project Summary" report.
[INFO] Generating "Source Repository" report.
[INFO]
------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO]
------------------------------------------------------------------------
[INFO] Username isn't defined.
[INFO]
------------------------------------------------------------------------
[INFO] Trace
java.lang.IllegalArgumentException: Username isn't defined.
        at org.apache.maven.scm.provider.cvslib.repository.CvsScmProviderRepository.getCvsRootForCvsPass(CvsScmProviderRepository.java:105)
        at org.apache.maven.scm.provider.cvslib.repository.CvsScmProviderRepository.getCvsRoot(CvsScmProviderRepository.java:73)
        at org.apache.maven.report.projectinfo.ScmReport$ScmRenderer.anonymousAccessCVS(ScmReport.java:457)
        at org.apache.maven.report.projectinfo.ScmReport$ScmRenderer.renderAnonymousAccessSection(ScmReport.java:276)
        at org.apache.maven.report.projectinfo.ScmReport$ScmRenderer.renderBody(ScmReport.java:183)
        at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:65)
        at org.apache.maven.report.projectinfo.ScmReport.executeReport(ScmReport.java:87)
        at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:101)
        at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:139)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:269)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:101)
        at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:129)
        at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:96)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:324)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO]
------------------------------------------------------------------------
[INFO] Total time: 28 seconds
[INFO] Finished at: Mon Aug 18 16:32:28 CEST 2008 [INFO] Final Memory: 54M/347M [INFO]
------------------------------------------------------------------------
```

---

**Affects:** 2.0.1

1 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Barend Put](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barend)** commented

I get the same stack trace.

Regardless of which CVS implementation is used,  I'd say that this report shouldn't fail if the credentials aren't inlined in the URL (e.g. when relying on settings.xml in ~/.m2 for authn).

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Can someone please provide an example project for this.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
