### ISSUE TITLE
[MPIR-135] NPE if license URL is not defined

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-project-info-reports-plugin#434]
**[Andreas Höhmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ahoehma)** opened **[MPIR-135](https://issues.apache.org/jira/browse/MPIR-135?redirect=false)** and commented

[INFO] [site:site]
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.report.projectinfo.LicenseReport.getLicenseURL(LicenseReport.java:156)
at org.apache.maven.report.projectinfo.LicenseReport.canGenerateReport(LicenseReport.java:114)
at org.apache.maven.plugins.site.AbstractSiteRenderingMojo.filterReports(AbstractSiteRenderingMojo.java:177)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:81)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:49
9)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.jav
a:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
$
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.1

1 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Andreas Höhmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ahoehma)** commented

\<licenses>
\<license>
\<name>Siemens\</name>
\<distribution>manual\</distribution>
\<comments>Siemens License\</comments>
\</license>
\</licenses>

**Comment by jira-importer** [comment]
**[Andreas Höhmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ahoehma)** commented

if i define a \<url>\</url> the the file-listing of the base-dir of the artifact is displayed as license ... hmm ?!

**Comment by jira-importer** [comment]
**[Benno Markiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bm97)** commented

The reason is the comparison using a null string.

Line 156:
Actual:
if ( urlValidator.isValid( url ) || url.startsWith( "file://" ) )
Fix        
if ( urlValidator.isValid( url ) || StringUtils.defaultString(url).startsWith( "file://" )  )

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

fixed in [748487](http://svn.apache.org/viewvc?rev=748487&view=rev)

**Comment by jira-importer** [comment]
**[David J. M. Karlsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=david@davidkarlsen.com)** commented

This happens in offline mode as well (-o).

[INFO] [site:site]
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.report.projectinfo.LicenseReport.getLicenseURL(Licen
seReport.java:156)
at org.apache.maven.report.projectinfo.LicenseReport.canGenerateReport(L
icenseReport.java:114)
at org.apache.maven.plugins.site.AbstractSiteRenderingMojo.filterReports
(AbstractSiteRenderingMojo.java:177)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:81)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:483)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:678)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLi
fecycle(DefaultLifecycleExecutor.java:540)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:519)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:371)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:332)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:181)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:356)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 minute 27 seconds
[INFO] Finished at: Sun Apr 05 18:50:26 CEST 2009
[INFO] Final Memory: 43M/93M
[INFO] ------------------------------------------------------------------------

**Comment by jira-importer** [comment]
**[Martin Grigorov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=martin-g)** commented

I want to confirm that I face the same NPE like David when Maven is started in offline mode.
