### ISSUE TITLE
[MPIR-147] Dependencies report hangs while accessing SSL site. Connection never closes

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-project-info-reports-plugin#443]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** opened **[MPIR-147](https://issues.apache.org/jira/browse/MPIR-147?redirect=false)** and commented

mvn site hangs while generating the reports (dump below). This is 100% reproducible.

This happens while contacting maven-repository.dev.java.net. The connection is opened and never closed. The connection to this external repository was done successfully several time in the same build.

Notes:
* a timeout would be useful:
  at org.apache.maven.wagon.providers.http.LightweightHttpWagon.resourceExists(LightweightHttpWagon.java:312)
  at org.apache.maven.report.projectinfo.dependencies.RepositoryUtils.dependencyExistsInRepo(RepositoryUtils.java:219)

* for some reason, the site report bypass our corporate repository (nexus). Cf MPIR-137

* workaround is to enable
  \<dependencyLocationsEnabled>false\</dependencyLocationsEnabled>
  \<dependencyDetailsEnabled>false\</dependencyDetailsEnabled>
  as done in MPIR-137

```
Full thread dump Java HotSpot(TM) Client VM (1.5.0_16-133 mixed mode):

"AWT-AppKit" daemon prio=5 tid=0x01038530 nid=0xa0110fa0 runnable [0x00000000..0xbfffe818]

"Low Memory Detector" daemon prio=5 tid=0x01009030 nid=0x805800 runnable [0x00000000..0x00000000]

"CompilerThread0" daemon prio=9 tid=0x01008580 nid=0x812c00 waiting on condition [0x00000000..0xb0b077d8]

"Signal Dispatcher" daemon prio=9 tid=0x01008130 nid=0x811e00 waiting on condition [0x00000000..0x00000000]

"Finalizer" daemon prio=8 tid=0x01007860 nid=0x819200 in Object.wait() [0xb0a05000..0xb0a05d90]
        at java.lang.Object.wait(Native Method)
        - waiting on <0x0a440228> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:120)
        - locked <0x0a440228> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:136)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:159)

"Reference Handler" daemon prio=10 tid=0x01007480 nid=0x817800 in Object.wait() [0xb0984000..0xb0984d90]
        at java.lang.Object.wait(Native Method)
        - waiting on <0x0a4402b0> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Object.java:474)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:116)
        - locked <0x0a4402b0> (a java.lang.ref.Reference$Lock)

"main" prio=5 tid=0x01001570 nid=0xb0801000 runnable [0xb07fe000..0xb0800148]
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:129)
        at com.sun.net.ssl.internal.ssl.InputRecord.readFully(InputRecord.java:293)
        at com.sun.net.ssl.internal.ssl.InputRecord.read(InputRecord.java:331)
        at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:723)
        - locked <0x05a4ba78> (a java.lang.Object)
        at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:680)
        at com.sun.net.ssl.internal.ssl.AppInputStream.read(AppInputStream.java:75)
        - locked <0x05a4bb28> (a com.sun.net.ssl.internal.ssl.AppInputStream)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:218)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:256)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:313)
        - locked <0x06b58100> (a java.io.BufferedInputStream)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:681)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:626)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:957)
        - locked <0x06b56708> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:367)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:318)
        at org.apache.maven.wagon.providers.http.LightweightHttpWagon.resourceExists(LightweightHttpWagon.java:312)
        at org.apache.maven.report.projectinfo.dependencies.RepositoryUtils.dependencyExistsInRepo(RepositoryUtils.java:219)
        at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.printArtifactsLocations(DependenciesRenderer.java:1122)
        at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderSectionDependencyRepositoryLocations(DependenciesRenderer.java:641)
        at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderBody(DependenciesRenderer.java:274)
        at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:65)
        at org.apache.maven.report.projectinfo.DependenciesReport.executeReport(DependenciesReport.java:239)
        at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:90)
        at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:139)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:269)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:101)
        at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:129)
        at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:96)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

"VM Thread" prio=9 tid=0x01006bd0 nid=0x816a00 runnable

"VM Periodic Task Thread" prio=9 tid=0x01009b70 nid=0x806600 waiting on condition

"Exception Catcher Thread" prio=10 tid=0x01001790 nid=0x80ac00 runnable 
```

---

**Affects:** 2.1

4 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

I can't reproduce it but I added a time out and bump to wagon beta-5 in r748489|http://svn.apache.org/viewvc?rev=748489&view=rev. HTH

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

I revert the changes due to a conflict version for wagon between core and plugin

**Comment by jira-importer** [comment]
**[Victor Volle](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vrvolle)** commented

I have the same symptoms (I use Nexus as a repository proxy):

Full thread dump Java HotSpot(TM) Client VM (1.5.0_19-137 mixed mode, sharing):

"MultiThreadedHttpConnectionManager cleanup" daemon prio=5 tid=0x01054520 nid=0x9f6400 in Object.wait() [0xb1011000..0xb1011d90]
at java.lang.Object.wait(Native Method)
- waiting on <0x0e410060> (a java.lang.ref.ReferenceQueue$Lock)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:120)
- locked <0x0e410060> (a java.lang.ref.ReferenceQueue$Lock)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:136)
  at hidden.org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$ReferenceQueueThread.run(MultiThreadedHttpConnectionManager.java:1122)

"pool-1-thread-5" prio=5 tid=0x0101fec0 nid=0x876800 in Object.wait() [0xb0f0f000..0xb0f0fd90]
at java.lang.Object.wait(Native Method)
- waiting on <0x0fe1efc0> (a hidden.edu.emory.mathcs.backport.java.util.concurrent.LinkedBlockingQueue$SerializableLock)
  at java.lang.Object.wait(Object.java:474)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:316)
- locked <0x0fe1efc0> (a hidden.edu.emory.mathcs.backport.java.util.concurrent.LinkedBlockingQueue$SerializableLock)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:994)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1054)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)
  at java.lang.Thread.run(Thread.java:613)

"pool-1-thread-4" prio=5 tid=0x0101fba0 nid=0x875a00 in Object.wait() [0xb0e8e000..0xb0e8ed90]
at java.lang.Object.wait(Native Method)
- waiting on <0x0fe1efc0> (a hidden.edu.emory.mathcs.backport.java.util.concurrent.LinkedBlockingQueue$SerializableLock)
  at java.lang.Object.wait(Object.java:474)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:316)
- locked <0x0fe1efc0> (a hidden.edu.emory.mathcs.backport.java.util.concurrent.LinkedBlockingQueue$SerializableLock)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:994)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1054)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)
  at java.lang.Thread.run(Thread.java:613)

"pool-1-thread-3" prio=5 tid=0x0101f850 nid=0x874c00 in Object.wait() [0xb0e0d000..0xb0e0dd90]
at java.lang.Object.wait(Native Method)
- waiting on <0x0fe1efc0> (a hidden.edu.emory.mathcs.backport.java.util.concurrent.LinkedBlockingQueue$SerializableLock)
  at java.lang.Object.wait(Object.java:474)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:316)
- locked <0x0fe1efc0> (a hidden.edu.emory.mathcs.backport.java.util.concurrent.LinkedBlockingQueue$SerializableLock)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:994)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1054)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)
  at java.lang.Thread.run(Thread.java:613)

"pool-1-thread-2" prio=5 tid=0x0101f430 nid=0x81c000 in Object.wait() [0xb0d8c000..0xb0d8cd90]
at java.lang.Object.wait(Native Method)
- waiting on <0x0fe1efc0> (a hidden.edu.emory.mathcs.backport.java.util.concurrent.LinkedBlockingQueue$SerializableLock)
  at java.lang.Object.wait(Object.java:474)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:316)
- locked <0x0fe1efc0> (a hidden.edu.emory.mathcs.backport.java.util.concurrent.LinkedBlockingQueue$SerializableLock)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:994)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1054)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)
  at java.lang.Thread.run(Thread.java:613)

"pool-1-thread-1" prio=5 tid=0x0101f2b0 nid=0x81b200 in Object.wait() [0xb0c8a000..0xb0c8ad90]
at java.lang.Object.wait(Native Method)
- waiting on <0x0fe1efc0> (a hidden.edu.emory.mathcs.backport.java.util.concurrent.LinkedBlockingQueue$SerializableLock)
  at java.lang.Object.wait(Object.java:474)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:316)
- locked <0x0fe1efc0> (a hidden.edu.emory.mathcs.backport.java.util.concurrent.LinkedBlockingQueue$SerializableLock)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:994)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1054)
  at hidden.edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)
  at java.lang.Thread.run(Thread.java:613)

"Low Memory Detector" daemon prio=5 tid=0x01009020 nid=0x806600 runnable [0x00000000..0x00000000]

"CompilerThread0" daemon prio=9 tid=0x01008570 nid=0x805800 waiting on condition [0x00000000..0xb0b077d8]

"Signal Dispatcher" daemon prio=9 tid=0x01008120 nid=0x817600 waiting on condition [0x00000000..0x00000000]

"Finalizer" daemon prio=8 tid=0x01007980 nid=0x815600 in Object.wait() [0xb0a05000..0xb0a05d90]
at java.lang.Object.wait(Native Method)
- waiting on <0x0fd1b420> (a java.lang.ref.ReferenceQueue$Lock)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:120)
- locked <0x0fd1b420> (a java.lang.ref.ReferenceQueue$Lock)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:136)
  at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:159)

"Reference Handler" daemon prio=10 tid=0x010075c0 nid=0x813e00 in Object.wait() [0xb0984000..0xb0984d90]
at java.lang.Object.wait(Native Method)
- waiting on <0x0fd1b4a8> (a java.lang.ref.Reference$Lock)
  at java.lang.Object.wait(Object.java:474)
  at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:116)
- locked <0x0fd1b4a8> (a java.lang.ref.Reference$Lock)

"main" prio=5 tid=0x010014c0 nid=0xb0801000 runnable [0xb07fe000..0xb0800148]
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(SocketInputStream.java:129)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:218)
at java.io.BufferedInputStream.read(BufferedInputStream.java:235)
- locked <0x0dd7c410> (a java.io.BufferedInputStream)
  at hidden.org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
  at hidden.org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
  at hidden.org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
  at hidden.org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
  at hidden.org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)
  at hidden.org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
  at hidden.org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
  at hidden.org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
  at hidden.org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
  at hidden.org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
  at hidden.org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
  at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:446)
  at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.resourceExists(AbstractHttpClientWagon.java:396)
  at org.apache.maven.report.projectinfo.dependencies.RepositoryUtils.dependencyExistsInRepo(RepositoryUtils.java:219)
  at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.printArtifactsLocations(DependenciesRenderer.java:1122)
  at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderSectionDependencyRepositoryLocations(DependenciesRenderer.java:641)
  at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderBody(DependenciesRenderer.java:274)
  at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:65)
  at org.apache.maven.report.projectinfo.DependenciesReport.executeReport(DependenciesReport.java:239)
  at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:90)
  at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:139)
  at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:269)
  at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:101)
  at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:133)
  at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:100)
  at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:483)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:678)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:540)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:519)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:371)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:332)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
  at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:41)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:585)
  at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
  at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
  at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
  at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

"VM Thread" prio=9 tid=0x01006d20 nid=0x813000 runnable

"VM Periodic Task Thread" prio=9 tid=0x0100a7b0 nid=0x807400 waiting on condition

"Exception Catcher Thread" prio=10 tid=0x010016e0 nid=0x80ac00 runnable

**Comment by jira-importer** [comment]
**[Amit Mujawar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=amit10may)** commented

Is it going to be addressed in any of the next Maven releases?
I wonder why is this not a common issue among the maven users.
mvn site is something most of them would be using and if all of them are wasting so much time on the build it should have been on high priority in maven issue fixes.

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

I bumped to latest wagon r1040075 (snap deployed). Confirm if it solves the pb.
