### ISSUE TITLE
[MPIR-159] ZipException during "mvn clean compile site"

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-project-info-reports-plugin#450]
**[Pawel Paprota](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ppawel)** opened **[MPIR-159](https://issues.apache.org/jira/browse/MPIR-159?redirect=false)** and commented

When running "mvn clean compile site" I get the exception below during generation of JAR dependency report. This is in a multi module project with parent A and child modules B and C. Also B depends on C. Exception occurs when generating site for module B.

```
[INFO] Generating "Dependencies" report.
[WARNING] The parameter 'dependencyLocationsEnabled' is ignored in offline mode.
[ERROR] IOException: Is a directory
java.util.zip.ZipException: Is a directory
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:203)
	at java.util.jar.JarFile.<init>(JarFile.java:132)
	at java.util.jar.JarFile.<init>(JarFile.java:97)
	at org.apache.maven.shared.jar.JarAnalyzer.<init>(JarAnalyzer.java:102)
	at org.apache.maven.report.projectinfo.dependencies.Dependencies.getJarDependencyDetails(Dependencies.java:282)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.hasSealed(DependenciesRenderer.java:1278)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderSectionDependencyFileDetails(DependenciesRenderer.java:423)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderBody(DependenciesRenderer.java:268)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:65)
	at org.apache.maven.report.projectinfo.DependenciesReport.executeReport(DependenciesReport.java:239)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:90)
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:139)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:269)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:101)
	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:133)
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:100)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:453)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:559)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:500)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:479)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:331)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:292)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:301)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

---

**Affects:** 2.1

**Attachments:**
- [test-project.tgz](https://issues.apache.org/jira/secure/attachment/12717650/test-project.tgz) (_1.75 kB_)

**Issue Links:**
- [MSHARED-87](https://issues.apache.org/jira/browse/MSHARED-87) ZipException throw by SDK's JarFile constructor may lack file name

2 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

Is your project an open source project ?
It's an order to have a project to test this issue.
Or can you provide a simple project in order to reproduce this ?
Thanks !

**Comment by jira-importer** [comment]
**[Pawel Paprota](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ppawel)** commented

I attach a test project that I am using during Cobertura plugin development. To reproduce this issue simply do "mvn clean compile site" in the parent project.

**Comment by jira-importer** [comment]
**[Manfred Schürhoff](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=manfredjs)** commented

I'm having the same issue when I run "mvn clean compile site-deploy" on our TeamCity buildserver (linux).
When I run the same command on my local PC (windows) it runs OK (no ZipException).
The ZipException doesn't seem to occur for every module being build.

Did anybody find a solution for this yet?

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

upgrade to maven-shared-jar.
I can't reproduce the issue with your attached it.
So can you test this with your project ?
