### ISSUE TITLE
[MPIR-214] IOException when generating dependency report in a multi-module build

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-project-info-reports-plugin#497]
**[Julien HENRY](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henryju)** opened **[MPIR-214](https://issues.apache.org/jira/browse/MPIR-214?redirect=false)** and commented

Running mvn clean site on my project produce the following error:

```
[ERROR] IOException: D:\Projects\jwebunit\jwebunit-commons-tests\target\classes (Acces denied)
java.io.FileNotFoundException: D:\Projects\jwebunit\jwebunit-commons-tests\target\classes (Acces denied)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:114)
        at java.util.jar.JarFile.<init>(JarFile.java:135)
        at java.util.jar.JarFile.<init>(JarFile.java:99)
        at org.apache.maven.shared.jar.JarAnalyzer.<init>(JarAnalyzer.java:105)
        at org.apache.maven.report.projectinfo.dependencies.Dependencies.getJarDependencyDetails(Dependencies.java:273)
        at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.hasSealed(DependenciesRenderer.java:1374)
        at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderSectionDependencyFileDetails(DependenciesRenderer.java:544)
        at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderBody(DependenciesRenderer.java:271)
```

It doesn't prevent the build to complete.

You can reproduce on the project:
https://jwebunit.svn.sourceforge.net/svnroot/jwebunit/trunk

Build instructions (need toolchains):
http://jwebunit.sourceforge.net/building-maven.html#Installing_Maven

Running mvn clean project-info-reports:dependencies works fine so I guess there is a bad interaction with another report.

---

**Affects:** 2.3.1

**Attachments:**
- [bug dependency.PNG](https://issues.apache.org/jira/secure/attachment/12717699/bug+dependency.PNG) (_7.46 kB_)

**Issue Links:**
- [MPIR-220](https://issues.apache.org/jira/browse/MPIR-220) IOException: Failed to open file During Site generation
 (_**"is duplicated by"**_)
- [MPIR-222](https://issues.apache.org/jira/browse/MPIR-222) Error reported for ZipException caused by dependency of type pom
 (_**"is duplicated by"**_)

2 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Lukas Theussl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ltheussl)** commented

What exactly is the bug? Is there something missing in the report? This is just an exception that is caught and logged in error mode but I see no bug here.

**Comment by jira-importer** [comment]
**[Julien HENRY](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henryju)** commented

Look at the attached screenshot. This is an extract of the "Dependency File Details" section.

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

fixed in [r1103555](http://svn.apache.org/viewvc?rev=1103555&view=rev)
