### ISSUE TITLE
[MPIR-240] NullPointerException thrown during Dependencies report

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-project-info-reports-plugin#513]
**[Coda Hale](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=codahale)** opened **[MPIR-240](https://issues.apache.org/jira/browse/MPIR-240?redirect=false)** and commented

This POM:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example</groupId>
    <artifactId>maven-dependencies-bug</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>com.sun.jersey</groupId>
            <artifactId>jersey-server</artifactId>
            <version>1.12</version>
        </dependency>
    </dependencies>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>3.0</version>
                <configuration>
                    <reportPlugins>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-project-info-reports-plugin</artifactId>
                            <version>2.4</version>
                        </plugin>
                    </reportPlugins>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

Throws this exception:

```
$ mvn -e clean site

[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building maven-dependencies-bug 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ maven-dependencies-bug ---
[INFO] Deleting /private/tmp/maven-jersey-poop/target
[INFO] 
[INFO] --- maven-site-plugin:3.0:site (default-site) @ maven-dependencies-bug ---
[INFO] configuring report plugin org.apache.maven.plugins:maven-project-info-reports-plugin:2.4
[WARNING] No project URL defined - decoration links will not be relativized!
[INFO] Rendering site with org.apache.maven.skins:maven-default-skin:jar:1.0 skin.
[INFO] Generating "Distribution Management" report    --- maven-project-info-reports-plugin:2.4
[INFO] Generating "About" report    --- maven-project-info-reports-plugin:2.4
[INFO] Generating "Dependencies" report    --- maven-project-info-reports-plugin:2.4
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.978s
[INFO] Finished at: Fri Feb 24 14:05:06 PST 2012
[INFO] Final Memory: 13M/75M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.0:site (default-site) on project maven-dependencies-bug: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.0:site failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.0:site (default-site) on project maven-dependencies-bug: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.0:site failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.0:site failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.NullPointerException
	at java.util.Collections.addAll(Collections.java:3836)
	at sun.security.ssl.AbstractTrustManagerWrapper.<init>(SSLContextImpl.java:778)
	at sun.security.ssl.SSLContextImpl.chooseTrustManager(SSLContextImpl.java:133)
	at sun.security.ssl.SSLContextImpl.engineInit(SSLContextImpl.java:89)
	at javax.net.ssl.SSLContext.init(SSLContext.java:283)
	at org.apache.maven.report.projectinfo.ProjectInfoReportUtils.getURLConnection(ProjectInfoReportUtils.java:347)
	at org.apache.maven.report.projectinfo.ProjectInfoReportUtils.getContent(ProjectInfoReportUtils.java:185)
	at org.apache.maven.report.projectinfo.ProjectInfoReportUtils.getContent(ProjectInfoReportUtils.java:102)
	at org.apache.maven.report.projectinfo.ProjectInfoReportUtils.getContent(ProjectInfoReportUtils.java:87)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.blacklistRepositoryMap(DependenciesRenderer.java:709)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderSectionDependencyRepositoryLocations(DependenciesRenderer.java:756)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderBody(DependenciesRenderer.java:279)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:79)
	at org.apache.maven.report.projectinfo.DependenciesReport.executeReport(DependenciesReport.java:196)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:190)
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:219)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:317)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:134)
	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

It's particular to the `com.sun.jersey:jersey-server` dependency.

---

**Affects:** 2.4

1 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Cannot reproduce with Maven 3.2.2, Site Plugin 3.4.1-SNAPSHOT and MPIR 2.7.

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building maven-dependencies-bug 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ maven-dependencies-bug ---
[INFO] Deleting /home/mosipov/Projekte/MPIR-240/target
[INFO] 
[INFO] --- maven-site-plugin:3.4.1-SNAPSHOT:site (default-site) @ maven-dependencies-bug ---
[INFO] configuring report plugin org.apache.maven.plugins:maven-project-info-reports-plugin:2.7
[WARNING] No project URL defined - decoration links will not be relativized!
[INFO] Rendering site with org.apache.maven.skins:maven-default-skin:jar:1.0 skin.
[INFO] Generating "About" report                --- maven-project-info-reports-plugin:2.7:index
[INFO] Generating "Plugin Management" report    --- maven-project-info-reports-plugin:2.7:plugin-management
[INFO] Generating "Distribution Management" report --- maven-project-info-reports-plugin:2.7:distribution-management
[INFO] Generating "Dependency Information" report --- maven-project-info-reports-plugin:2.7:dependency-info
[INFO] Generating "Source Repository" report    --- maven-project-info-reports-plugin:2.7:scm
[INFO] Generating "Mailing Lists" report        --- maven-project-info-reports-plugin:2.7:mailing-list
[INFO] Generating "Issue Tracking" report       --- maven-project-info-reports-plugin:2.7:issue-tracking
[INFO] Generating "Continuous Integration" report --- maven-project-info-reports-plugin:2.7:cim
[INFO] Generating "Project Plugins" report      --- maven-project-info-reports-plugin:2.7:plugins
[INFO] Generating "Project License" report      --- maven-project-info-reports-plugin:2.7:license
[INFO] Generating "Project Team" report         --- maven-project-info-reports-plugin:2.7:project-team
[INFO] Generating "Project Summary" report      --- maven-project-info-reports-plugin:2.7:summary
[INFO] Generating "Dependencies" report         --- maven-project-info-reports-plugin:2.7:dependencies
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.300 s
[INFO] Finished at: 2014-07-05T20:07:01+02:00
[INFO] Final Memory: 15M/46M
[INFO] ------------------------------------------------------------------------
```
