### ISSUE TITLE
[MPIR-247] "Comparison method violates its general contract!" while generating site

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-project-info-reports-plugin#519]
**[Mirek Hankus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mhankus)** opened **[MPIR-247](https://issues.apache.org/jira/browse/MPIR-247?redirect=false)** and commented

While generating site, I'm getting exception as follows.

```
message : Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.1:site (default-site) on project netpr-aggregator: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.1:site failed: Comparison method violates its general contract!
cause : Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.1:site failed: Comparison method violates its general contract!
Stack trace : 
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.1:site (default-site) on project netpr-aggregator: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.1:site failed: Comparison method violates its general contract!
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.jvnet.hudson.maven3.launcher.Maven3Launcher.main(Maven3Launcher.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:329)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:239)
	at org.jvnet.hudson.maven3.agent.Maven3Main.launch(Maven3Main.java:158)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:98)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:64)
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.1:site failed: Comparison method violates its general contract!
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 27 more
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:835)
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:453)
	at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:376)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:182)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:146)
	at java.util.Arrays.sort(Arrays.java:472)
	at java.util.Collections.sort(Collections.java:155)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.getDependencyRow(DependencyManagementRenderer.java:228)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderDependenciesForScope(DependencyManagementRenderer.java:204)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderDependenciesForAllScopes(DependencyManagementRenderer.java:153)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderSectionProjectDependencies(DependencyManagementRenderer.java:146)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderBody(DependencyManagementRenderer.java:132)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:79)
	at org.apache.maven.report.projectinfo.DependencyManagementReport.executeReport(DependencyManagementReport.java:116)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:190)
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:219)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:319)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:135)
	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 28 more

```

---

**Affects:** 2.4

**Attachments:**
- [MPIR-247.zip](https://issues.apache.org/jira/secure/attachment/12717706/MPIR-247.zip) (_3.25 kB_)

**Issue Links:**
- [MPIR-216](https://issues.apache.org/jira/browse/MPIR-216) Report on dependency-management throws Exceptions using version range for dependency

- [MNG-5568](https://issues.apache.org/jira/browse/MNG-5568) ComparableVersion's breaks contract for Comparable, in some edgecases the comparisons are not transitive
 (_**"depends upon"**_)

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

can you provide a sample project showing the problem?

**Comment by jira-importer** [comment]
**[Milos Kleint](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkleint)** commented

related is this netbeans issue: http://netbeans.org/bugzilla/show_bug.cgi?id=226100
we use maven's ComparableVersion for sorting the nexus indexer results. It keeps on popping here and there, only with jdk 1.7. It would be probably easier to dump the dependency info in DependencyManagementRenderer than our code (the result can contain thousands of items, dependency list will be shorter).

I've never got hold of a reproducible scenario.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

There is no way to fix this issue in MPIR. The only way will be to upgrade to 3.2.4. What I'll do in time is after the 3.2.4 release, I'll catch that exception and signal to the user that he should upgrade to Maven 3.2.4.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy), I'd like to take this on and create a fix + IT. Can you provide me a simple example based on the core fix to reproduce this issue or [Milos Kleint](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkleint)?

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

the core UT for MNG-5568 gives you version strings that cause the problem
now, I didn't really looked at injecting artifacts with such version into the report mojo to cause the failure

reading `DependencyManagementRenderer.getDependencyRow(DependencyManagementRenderer.java:228)`, it seems you'll require to have a dependencyManagement configured with a range for an artifact having this version problem

I don't know if the best solution is to find an artifact in central or create a local repo in the IT

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Yes, the try/catch was what I had in mind. IT is too much hassle for this edge case. Though, I cannot test the try/catch it would be like this:

```
 if ( versions.size() > 0 )
                {
                    
try {
            Collections.sort( versions );
} catch (IAE e) {
  if (e.getMessage().equals("...contract violation...") {
  throw new IllegalStateException("Dependencies cannot be sorted due to MNG-xxxx, please update to Maven 3.2.5 to resolve this ssue");
} else throw e;
}
                    
                    artifact.setVersion( versions.get( versions.size() - 1 ).toString() );
                    log.debug( "DependencyManagement resolved: " + artifact.getId() );
                }
```

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

yes
notice  that adding to the message the versions that cause the issue could be useful

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

OK, I will prepare a branch and will let you know to check it.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy), I have created a [branch](https://svn.apache.org/repos/asf/maven/plugins/branches/MPIR-247) now, please have a look.

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

that's the code I expected
I only wonder if we should only write a warning instead of failing the build: that report isn't that important that it requires a Maven update

notice I had a new look at creating an IT: found the artifact in central that Milos used to give us an example: `org.mortbay.jetty:jetty-util` http://repo.maven.apache.org/maven2/org/mortbay/jetty/jetty-util/ , with the 6.1H.5-beta, 6.0.1 and 6.1.0rc3 versions given in MNG-5568

I tried once again to do an IT, but couldn't manage to do it: even when I manage to have problematic versions in the range, it doesn't cause any failure since the retrieved list is already sorted

I'll attach the current IT I managed to do...

this work made me wonder why we were sorting the list: we don't really need to!

then I propose following change:

```java
// select latest, assuming pom information will be the most accurate
if ( versions.size() > 0 )
{
    // list is already sorted: no need to sort it once again (and cause MPIR-247)
    // Collections.sort( versions );
    // and if not perfectly sorted, not a big issue: version just used to get license info and url
    // of the artifact
        artifact.setVersion( versions.get( versions.size() - 1 ).toString() );
    log.debug( "DependencyManagement resolved: " + artifact.getId() );
}
```

it seems the most simple fix: no need to sort

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

here is the IT I prepared: I had to add a repo since metadata in central don't contain every versions available
it seems central publication got hit by the sorting bug :)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

The metadata file is far from being complete. Are you sure that it is already sorted? I presumed the file contains versions as they are added. Not necessarily sorted. E.g., 6.1.2, 6.2, 6.1.3, 6.2.1. Can this happen? Have a look at  [this](http://repo.maven.apache.org/maven2/net/fckeditor/java-core/maven-metadata.xml) example.

If this is negligible, I would throw away my branch and take your fix or turn my exception into a `log.error`.

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

in fact, order during execution is not strictly order of the repository, but as done by Maven core, while merging multiple repos, for example

but even with that, I'm not not sure the API enforces order.

Since we only want the latest, we could simple avoid Collections.sort and simply iterate over the collection and compare to keep the max.
And while writing this, we should simply use Collections.max() instead of Collections.sort(): here it is, I try this is the right answer, better than any previous!

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Way better, yes. According to the docs, `max()` iterates over the collection without sorting it. I will create another branch shortly.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Fixed with [r1649372](http://svn.apache.org/r1649372). Hervé, thank you very much for your help!

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

thank you for your patience: it was long, but the discussion was useful since we found an idea that has taken so long to come to mind...
