### ISSUE TITLE
[MPIR-252] Dependency Management report doesn't exclude system scoped dependencies

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-project-info-reports-plugin#524]
**[Martijn Verburg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=karianna)** opened **[MPIR-252](https://issues.apache.org/jira/browse/MPIR-252?redirect=false)** and commented

```
[WARNING] Unable to create Maven project for com.sun:tools:pom:localVersion from repository.
org.apache.maven.project.ProjectBuildingException: Error resolving project artifact: Failure to find com.sun:tools:pom:localVersion in http://ci.jclarity.com:8081/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of jclarity-central has elapsed or updates are forced for project com.sun:tools:pom:localVersion
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:296)
	at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:236)
	at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:251)
	at org.apache.maven.report.projectinfo.dependencies.RepositoryUtils.getMavenProjectFromRepository(RepositoryUtils.java:298)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.getDependencyRow(DependencyManagementRenderer.java:237)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderDependenciesForScope(DependencyManagementRenderer.java:204)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderDependenciesForAllScopes(DependencyManagementRenderer.java:157)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderSectionProjectDependencies(DependencyManagementRenderer.java:146)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependencyManagementRenderer.renderBody(DependencyManagementRenderer.java:132)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:79)
	at org.apache.maven.report.projectinfo.DependencyManagementReport.executeReport(DependencyManagementReport.java:112)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:190)
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:219)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:319)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:135)
	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Failure to find com.sun:tools:pom:localVersion in http://ci.jclarity.com:8081/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of jclarity-central has elapsed or updates are forced
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:193)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:286)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:285)
	... 37 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Failure to find com.sun:tools:pom:localVersion in http://ci.jclarity.com:8081/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of jclarity-central has elapsed or updates are forced
	at org.sonatype.aether.impl.internal.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:230)
	at org.sonatype.aether.impl.internal.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:204)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:427)
	... 41 more
```

---

**Affects:** 2.5.1

**Issue Links:**
- [MPIR-362](https://issues.apache.org/jira/browse/MPIR-362) Dependency Management report doesn't exclude system scoped dependencies
 (_**"is cloned by"**_)

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Was this a system-scoped dependency? What does it look like? (In other words: how can we reproduce it?)

**Comment by jira-importer** [comment]
**[Martijn Verburg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=karianna)** commented

In the dependency management section:

```
<dependency>
    <groupId>com.sun</groupId>
    <artifactId>tools</artifactId>
    <version>localVersion</version>
    <scope>system</scope>
    <systemPath>${toolsjar}</systemPath>
</dependency>
```

Where `${toolsJar}` is set by a property to be `${java.home}/../lib/tools.jar`

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Is this issue still valid?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

No reaction upon request.

**Comment by jira-importer** [comment]
**[Martijn Verburg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=karianna)** commented

Apologies, I wasn't getting notifications for this issue.  It's still a valid problem on mvn 3.3.9, jdk 1..8.0_66 with latest reporting plugins.

**Comment by jira-importer** [comment]
**[Martijn Verburg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=karianna)** commented

Still an issue with latest maven (3.3.9), JDK 1.8.0_66 and reporting plugins

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

While this might not solve the issue. both `system` scope and `tools.jar` will go away. It does not look like a MPIR problem per se.

**Comment by jira-importer** [comment]
**[Martijn Verburg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=karianna)** commented

Well they'll be going away in Java 9 yes, but that's now delayed until March 2017 and there's still the previous versions to support :-).

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Martijn, do you expect `system` to be excluded completely? One would need to remove that line: https://maven.apache.org/plugins/maven-project-info-reports-plugin/xref/org/apache/maven/report/projectinfo/dependencies/renderer/DependencyManagementRenderer.html#L161

Can someone of the affected try this locally and report?

**Comment by jira-importer** [comment]
**[Martijn Verburg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=karianna)** commented

I'm not 100% sure system scoped should be excluded, but it doesn't make sense to that particular one, so perhaps an exclusion filter needs to be allowed?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

What do you have in mind?

**Comment by jira-importer** [comment]
**[Martijn Verburg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=karianna)** commented

Perhaps add the capability for this dependency management report to exclude certain dependencies.  \<excludes>\<exclude>...\</exclude>\</excludes> as a workaround of sorts?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

An exclude would make the output useless as it would not reflect the real world. (imho)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Martijn Verburg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=karianna), can you provide me a sample project? Just added `tools.jar` to an empty project and did not receive an exception.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Are you able to provide a sample project now?

**Comment by jira-importer** [comment]
**[Martijn Verburg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=karianna)** commented

I can no longer repeat this problem either - many apologies for wasting time here.
