### ISSUE TITLE
[MPIR-275] NPE in DependenciesReport

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-project-info-reports-plugin#540]
**[Ian Brandt](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ian@ianbrandt.com)** opened **[MPIR-275](https://issues.apache.org/jira/browse/MPIR-275?redirect=false)** and commented

I suddenly started getting the same error as in MPIR-248, but with maven-project-info-reports-plugin 2.6 and maven-dependency-plugin 2.5.1.  I updated to maven-dependency-plugin 2.7, but no change.

The error occurs on my CI server, but not on my local machine.  Both reference the same Archiva proxy repository, but have separate local repositories.

The failure started on a manually triggered build.  There were no code changes from the build triggered by the last commit, and that build succeeded.  There were no POM or dependency changes going back at least another 5 commits, and all those builds succeeded as well.  There have been 6 subsequent builds, a mix of manually triggered and commit triggered ones, and they have all failed.  I enabled debug logging, but nothing is jumping out at me as abnormal.

Are there any further troubleshooting steps I should perform?  I could provide the debug log, but I'd have to scrub it a bit first.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.2:site (default-site) on project myproject: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.2:site failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.2:site (default-site) on project myproject: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.2:site failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.2:site failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.NullPointerException
	at org.apache.maven.report.projectinfo.dependencies.Dependencies.getJarDependencyDetails(Dependencies.java:243)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.hasSealed(DependenciesRenderer.java:1453)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderSectionDependencyFileDetails(DependenciesRenderer.java:547)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderBody(DependenciesRenderer.java:274)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:79)
	at org.apache.maven.report.projectinfo.DependenciesReport.executeReport(DependenciesReport.java:186)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:190)
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:219)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:319)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:135)
	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

---

**Affects:** 2.6

**Issue Links:**
- [MPIR-248](https://issues.apache.org/jira/browse/MPIR-248) NPE while DependenciesReport

**Comment by jira-importer** [comment]
**[Ian Brandt](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ian@ianbrandt.com)** commented

I tossed the local .m2 folder on my CI machine to force a re-download of all dependencies.  No change.

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

added one more level of check in [r1479923](http://svn.apache.org/r1479923)

**Comment by jira-importer** [comment]
**[Ian Brandt](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ian@ianbrandt.com)** commented

Thanks Herve!  I pulled down 2.7-SNAPSHOT from Github, built and deployed it to my local Archiva instance, and updated my POM accordingly.  Your change fixed my build.

For inquiring minds the new error handling logged:

```
[ERROR] Artifact: com.sun:tools:jar:1.5.0 has no file.
```

Looks like Struts 2.3.4 declares the dependency:

```
[DEBUG]       org.apache.struts:struts2-core:jar:2.3.4:compile
[DEBUG]          org.freemarker:freemarker:jar:2.3.19:compile
[DEBUG]          commons-fileupload:commons-fileupload:jar:1.2.2:compile
[DEBUG]          com.sun:tools:jar:1.5.0:system
```

I'll need to dig a bit deeper to figure out what changed in my CI environment to suddenly cause this to manifest.  Either way it works now.

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

I'm surprised, because:
1. you seem to have results from code already existing in version 2.6: see [the code](http://maven.apache.org/plugins/maven-project-info-reports-plugin/xref/org/apache/maven/report/projectinfo/dependencies/renderer/DependenciesRenderer.html#1416) (which shoud then give a stacktrace, AFAIK)
2. system scope should have been detected one test just before, not causing any error output

the test I added won't cause much harm, so I'll let it, but I'm still convinced it's not useful
