### ISSUE TITLE
[MPIR-279] Wrong hyperlinks on index and modules page

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-project-info-reports-plugin#544]
**[scolebourne2](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=scolebourne2)** opened **[MPIR-279](https://issues.apache.org/jira/browse/MPIR-279?redirect=false)** and commented

The attached zip is a complete multi-module build with the bug exposed. Run using "mvn clean site site:stage" to reproduce.

What is observed is that the navigation hyperlinks in the top left (added by the site plugin) are correctly defined as "target/staging/og-timeseries/index.html", whereas the hyperlinks in the middle of index.html and modules.html are incorrectly defined as "target/staging/projects/og-timeseries/index.html" - note the incorrect extra "projects".

The problem will occur because the child projects in the multi-module build are not immediate children of the parent/aggregator. Instead the structure is:

```
platform
 - pom.xml
 - projects
   - og-timeseries
     - pom.xml
```

The extra layer is being handled by the site plugin (by referring to the "distributionManagement.site.url"). It is not handled by this plugin.

As a side note, if "distributionManagement.site.url" is NOT set in the child projects, then the site will build consistently using "target/staging/projects/og-timeseries/index.html" everywhere.

This is no doubt related to MPIR-273.

---

**Affects:** 2.7

**Attachments:**
- [OG-Platform2.zip](https://issues.apache.org/jira/secure/attachment/12717630/OG-Platform2.zip) (_17.68 kB_)

**Issue Links:**
- [MPIR-285](https://issues.apache.org/jira/browse/MPIR-285) ModulesReport incorrectly contains indirect descendants
 (_**"is duplicated by"**_)
- [MPIR-292](https://issues.apache.org/jira/browse/MPIR-292) On the Modules report, the links to sub-sub-modules are not correctly generated
 (_**"is duplicated by"**_)
- [MPIR-303](https://issues.apache.org/jira/browse/MPIR-303) Backslash in multi-module project

- [MPIR-309](https://issues.apache.org/jira/browse/MPIR-309) The Integration test mpir-229 breaks on Apache Jenkins

- [MPIR-229](https://issues.apache.org/jira/browse/MPIR-229) The 'modules' report does not support 'url' elements using properties.

- [MPIR-273](https://issues.apache.org/jira/browse/MPIR-273) links to modules broken in modules.html of flat multimodule parent project

3 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Grzegorz Slowikowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gslowikowski)** commented

Do you want very simple test project showing the problem from Tibor's comment?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Not necessary, the attached one is fine and I have one at work which causes the faulty behavior.

**Comment by jira-importer** [comment]
**[Grzegorz Slowikowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gslowikowski)** commented

Works for me, thanks.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Is anyone able to help with the failiing unit test? I cannot commit and close otherwise.

**Comment by jira-importer** [comment]
**[Grzegorz Slowikowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gslowikowski)** commented

First of all add:

```java
this.localRepository = localRepository;
```

to ModulesRenderer's constructor.

This solves NPE, but then I have another exception.

```
testReport(org.apache.maven.report.projectinfo.ModulesReportTest)  Time elapsed: 1.25 sec  <<< ERROR!
java.lang.IllegalStateException: Unable to read local module POM
	at org.apache.maven.report.projectinfo.ModulesReport$ModulesRenderer.renderBody(ModulesReport.java:140)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:83)
	at org.apache.maven.report.projectinfo.ModulesReport.executeReport(ModulesReport.java:56)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
	at org.apache.maven.report.projectinfo.AbstractProjectInfoReport.execute(AbstractProjectInfoReport.java:223)
	at org.apache.maven.report.projectinfo.AbstractProjectInfoTestCase.generateReport(AbstractProjectInfoTestCase.java:198)
	at org.apache.maven.report.projectinfo.AbstractProjectInfoTestCase.generateReport(AbstractProjectInfoTestCase.java:182)
	at org.apache.maven.report.projectinfo.ModulesReportTest.testReport(ModulesReportTest.java:50)
Caused by: org.apache.maven.project.ProjectBuildingException: Cannot find parent: org.apache.maven.plugin.projectinfo.tests:dependency-convergence for project: org.apache.maven.plugin.projectinfo.tests:project1:jar:1.0-SNAPSHOT for project org.apache.maven.plugin.projectinfo.tests:project1:jar:1.0-SNAPSHOT
	at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1396)
	at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:823)
	at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.java:508)
	at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:217)
	at org.apache.maven.report.projectinfo.ModulesReport$ModulesRenderer.renderBody(ModulesReport.java:136)
	... 58 more
Caused by: org.apache.maven.project.ProjectBuildingException: POM 'org.apache.maven.plugin.projectinfo.tests:dependency-convergence' not found in repository: Unable to download the artifact from any repository

  org.apache.maven.plugin.projectinfo.tests:dependency-convergence:pom:1.0-SNAPSHOT

from the specified remote repositories:
  central (http://repo1.maven.org/maven2)

 for project org.apache.maven.plugin.projectinfo.tests:dependency-convergence
	at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:605)
	at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1392)
	... 62 more
Caused by: org.apache.maven.artifact.resolver.ArtifactNotFoundException: Unable to download the artifact from any repository

  org.apache.maven.plugin.projectinfo.tests:dependency-convergence:pom:1.0-SNAPSHOT

from the specified remote repositories:
  central (http://repo1.maven.org/maven2)


	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:228)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:90)
	at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:558)
	... 63 more
Caused by: org.apache.maven.wagon.ResourceDoesNotExistException: Unable to download the artifact from any repository
	at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:404)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:216)
	... 65 more
```

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Thanks, I have missed the `localRepository` completely. Though the exception does not make sense at all but I will have at look at it.

As a last resort, one could disable the unit test. Sadly but maybe necessary until someone finds the cause for that.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Stuart McCulloch give me the final tip on the dev mailing list. Test passes now. I will proceed with the merge later today.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Fixed with [r1639526](http://svn.apache.org/r1639526).

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

fixed in [r1641094](http://svn.apache.org/r1641094) MPIR-229 IT inadvertently broken:

> was both:
> 1. an existing IT weakness (missing distributionManagement section, which
>    cannot exist in real use case): I fixed the IT
> 
> 2. and a change in output in case no name defined in module pom: I reverted to
>    previous algorithm (use artifactId) instead of ugly "Unnamed g:a:v"

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

The name method was based off this: http://maven.apache.org/shared/maven-doxia-tools/xref/org/apache/maven/doxia/tools/DefaultSiteTool.html#1348
